//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Issuance = new HashSet<Issuance>();
        }
    
        public int id_books { get; set; }
        public string Title { get; set; }
        public Nullable<int> Author { get; set; }
        public Nullable<int> Co_Author { get; set; }
        public Nullable<int> Publisher { get; set; }
        public Nullable<int> Release_year { get; set; }
        public Nullable<int> Page_Count { get; set; }
        public string Department { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Authors Authors1 { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Publishers Publishers { get; set; }
        string price => Price.ToString();
        public string Price_Total => price.Substring(0, price.Length - 2);
        public string title => Title.Trim();

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issuance> Issuance { get; set; }
    }
}
