//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issuance
    {
        public int id_issuance { get; set; }
        public int Reader { get; set; }
        public int Book { get; set; }
        public System.DateTime Issue_Date { get; set; }
        public System.DateTime Est_Return_Date { get; set; }
        public Nullable<int> Extension_Period { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Readers Readers { get; set; }
        public string Is_Date => Issue_Date.ToString().Trim().Substring(0, 10);
        public string Est_Date => Est_Return_Date.ToString().Trim().Substring(0, 10);
        public string Re_Date => Return_Date.ToString().Trim().Substring(0, 10);
    }
}
