//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library
{
    using System;
    using System.Collections.Generic;
    using System.Net.Sockets;

    public partial class Readers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Readers()
        {
            this.Issuance = new HashSet<Issuance>();
        }
    
        public int id_reader_card { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string F_Name=>First_Name.Trim();
        public string M_Name=>Middle_Name.Trim();
        public string L_Name=>Last_Name.Trim();
        public string Full_Name => F_Name + " " + M_Name + " " + L_Name;
        public string Cut_Full_Name => F_Name + " " 
            + M_Name.Substring(0, 1) + "." 
            + L_Name.Substring(0, 1) + ".";
        public string BDay => Birthday.ToString().Trim().Substring(0, 10);
        public string address=>Address.Trim();
        public virtual Genders Genders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issuance> Issuance { get; set; }
    }
}
